Parameters:
  EC2Subnet:
    Default: '10.10.10.0/27'
    Description: Subnet for EC2 instances
    Type: String
  PuplicSubnetAZ2:
    Default: '10.10.10.96/27'
    Description: Subnet for EC2 instances
    Type: String
  MainSubnet:
    Default: '10.10.10.32/27'
    Description: Subnet for EC2 instances
    Type: String 
  SecondarySubnet:
    Default: '10.10.10.64/27'
    Description: Subnet for EC2 instances
    Type: String
  VPCNetworkCIDR:
    Default: '10.10.10.0/24'
    Description: Subnet for EC2 instances
    Type: String
  LoadBalancerPort:
    Default: 80
    Description: Load Balancer Port
    Type: String
  InstancePort:
    Default: 80
    Description: Instance Port
    Type: String

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCNetworkCIDR: !Ref VPCNetworkCIDR
      TemplateURL: https://s3.eu-central-1.amazonaws.com/Run/2.vpc.yaml
      TimeoutInMinutes: '60'
  
  PublicSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet: !Ref EC2Subnet
        VpcId: !GetAtt [ VPC, Outputs.VPC ]
        AZ: 0
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/3.subnet.public.yaml
      TimeoutInMinutes: '60'
  
  PublicSubnetAZ2:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet: !Ref PuplicSubnetAZ2
        VpcId: !GetAtt [ VPC, Outputs.VPC ]
        AZ: 1
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/3.subnet.public.yaml
      TimeoutInMinutes: '60'
  
  PrivateMainSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AZ: '0'
        RDSCIDR: !Ref MainSubnet  

        VpcId:
          !GetAtt [ VPC, Outputs.VPC ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/4.subnet.rds.yaml
      TimeoutInMinutes: '60'

  PrivateSecondarySubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AZ: '1'
        RDSCIDR: !Ref SecondarySubnet
        VpcId:
          !GetAtt [ VPC, Outputs.VPC ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/4.subnet.rds.yaml
      TimeoutInMinutes: '60'

  InternetGateway:
    DependsOn: VPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/6.gw.public.yaml
      TimeoutInMinutes: '60'

  AttachGatewayToVPC:
    DependsOn: 
    - InternetGateway
    - VPC
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        InternetGateway:
          !GetAtt [ InternetGateway, Outputs.InternetGateway ]
        VpcId:
          !GetAtt [ VPC, Outputs.VPC ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/7.gw.public.attach.yaml
      TimeoutInMinutes: '60'

  PrivateSubnetGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PrivateMainSubnet:
          !GetAtt [ PrivateMainSubnet, Outputs.RDSSubnet ]
        PrivateSecondarySubnet:
          !GetAtt [ PrivateSecondarySubnet, Outputs.RDSSubnet ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/5.subnet.group.rds.yaml
      TimeoutInMinutes: '60'

  RouteTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DestinationCidrBlock: '0.0.0.0/0'
        PublicSubnet: !GetAtt [ PublicSubnet, Outputs.PublicSubnet ]
        PublicSubnetAZ2: !GetAtt [ PublicSubnetAZ2, Outputs.PublicSubnet ]
        InternetGateway:
          !GetAtt [ InternetGateway, Outputs.InternetGateway ]
        VpcId:
          !GetAtt [ VPC, Outputs.VPC ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/8.route.table.public.yaml
      TimeoutInMinutes: '60'
  
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCNetworkCIDR: !Ref VPCNetworkCIDR
        VpcId: !GetAtt [ VPC, Outputs.VPC ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/18.security.groups.yaml
      TimeoutInMinutes: '60'

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DBName: 'magento0db'
        DBInstanceClass: 'db.t2.micro'
        AllocatedStorage: '5'
        DBMasterUsername: 'admin'
        DBMasterUserPassword: 'Password1!'
        PrivateSubnetGroup: !GetAtt [ PrivateSubnetGroup, Outputs.PrivateSubnetGroup ]
        DBBackupRetentionPeriod: '7'
        SecurityGroupRDS: !GetAtt [ SecurityGroups, Outputs.SecurityGroupRDS ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/10.rds.multi.az.yaml
      TimeoutInMinutes: '60'
  
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      IAMProfile: !GetAtt [ IAMStack, Outputs.IAMProfile ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/13.iam.role.profile.yaml
      TimeoutInMinutes: '60'
  
 EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EFSSecurityGroup: !GetAtt [ SecurityGroups, Outputs.EFSSecurityGroup ]
        PrivateSubnets: 
          !Join 
            - ","
            - - !GetAtt PrivateMainSubnet.Outputs.RDSSubnet
              - !GetAtt PrivateSecondarySubnet.Outputs.RDSSubnet
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/14.efs.az.enabled.yaml
      TimeoutInMinutes: '60'

  PublicLoadBalancer:
    DependsOn: 
    - InternetGateway
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        LoadBalancerPort: !Ref LoadBalancerPort
        InstancePort: !Ref InstancePort
        PublicSubnet: !GetAtt [ PublicSubnet, Outputs.PublicSubnet ]
        PublicSubnetAZ2: !GetAtt [ PublicSubnetAZ2, Outputs.PublicSubnet ]
        ELBSecurityGroup: !GetAtt SecurityGroups.Outputs.PublicLoadBalancerSecurityGroup
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/17.elb.public.yaml
      TimeoutInMinutes: '60'

  AutoScalingGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IAMARN: !GetAtt [ IAMStack, Outputs.IAMARN ]
        MagentoImageId: 'ami-0a2b7e2d7ab039b03'
        InstanceType: 't2.micro'
        WebServerMinSize: '2'
        WebServerMaxSize: '4'
        DesiredCapacity: '2'
        MainSubnet: !GetAtt [ PrivateMainSubnet, Outputs.RDSSubnet ]
        SecondarySubnet: !GetAtt [ PrivateSecondarySubnet, Outputs.RDSSubnet ]
        EC2SecurityGroup: !GetAtt SecurityGroups.Outputs.EC2SecurityGroup
        PublicLoadBalancer: !GetAtt [ PublicLoadBalancer, Outputs.PublicLoadBalancer ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/16.auto.scaling.yaml
      TimeoutInMinutes: '60'

  S3Buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      IAMProfile: !GetAtt [ IAMStack, Outputs.IAMProfile ]
      TemplateURL: https://s3.eu-central-1.amazonaws.com/magento.stack/19.s3.buckets.yaml
      TimeoutInMinutes: '60'
