Parameters:
  WebServerMinSize:
    Description: Web Server Min Size
    Type: String
  WebServerMaxSize:
    Description: Web Server Max Size
    Type: String
  DesiredCapacity:
    Description: WebServer Desired Capacity
    Type: String
  MainSubnet:
    Description: EC2 subnets
    Type: String  
  SecondarySubnet:
    Description: EC2 subnets
    Type: String
  MagentoImageId:
    Description: Magento Image Id
    Type: String
  InstanceType:
    Description: Instance Type
    Type: String
  EC2SecurityGroup:
    Description: Security Group Instance
    Type: String
  IAMARN:
    Description: IAM ARN
    Type: String
  PublicLoadBalancer:
    Description: Public Load Balancer
    Type: String

Resources:
  EC2LunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !Ref MagentoImageId
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
        - !Ref EC2SecurityGroup
        IamInstanceProfile: 
          Arn: !Ref IAMARN

  AutoScaling:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: !Ref WebServerMinSize
      MaxSize: !Ref WebServerMaxSize
      DesiredCapacity: !Ref DesiredCapacity
      LoadBalancerNames: 
        - !Ref PublicLoadBalancer
      MixedInstancesPolicy:
        InstancesDistribution: 
          OnDemandAllocationStrategy: prioritized
          OnDemandPercentageAboveBaseCapacity: 50
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 2
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref EC2LunchTemplate
            Version: '1'
          Overrides:
            - InstanceType: 't2.micro'
            - InstanceType: 't3.nano'
      VPCZoneIdentifier:
        - !Ref MainSubnet
        - !Ref SecondarySubnet
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Web Server
        PropagateAtLaunch: true

  
  WebServerTargetTrackingScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScaling
      Cooldown: '60'
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 90.0