Parameters:
  PublicSubnet:
    Description: Public Subnet for AZ1
    Type: String 
  PublicSubnetAZ2:
    Description: Public Subnet for AZ2
    Type: String 
  ELBSecurityGroup:
    Description: Security Group Instance
    Type: String
  LoadBalancerPort:
    Description: Load Balancer Port
    Type: String
  InstancePort:
    Description: Instance Port
    Type: String
  SSLCertificateId:
    Description: AWS Certificate ID
    Type: String

Resources:
  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet
        - !Ref PublicSubnetAZ2
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Listeners:
        - LoadBalancerPort: !Ref LoadBalancerPort
          InstancePort: !Ref InstancePort
          Protocol: HTTPS
          InstanceProtocol: HTTP
          SSLCertificateId: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SSLCertificateId}
      Tags:
      - Key: Name
        Value: MagentoWebserverALB
  
Outputs:
  PublicLoadBalancer:
    Description: 'RDSSubnet'
    Value: !Ref PublicLoadBalancer
  DNS:
    Value: !GetAtt PublicLoadBalancer.DNSName
