Parameters:
  PublicSubnet:
    Description: Public Subnet
    Type: String  
  SecurityGroupInstance:
    Description: Security Group Instance
    Type: String
  LoadBalancerPort:
    Description: Load Balancer Port
    Type: String
  InstancePort:
    Description: Instance Port
    Type: String

Resources:
  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      #Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet
      SecurityGroups:
        - !Ref SecurityGroupInstance
      Listeners:
        - LoadBalancerPort: !Ref LoadBalancerPort
          InstancePort: !Ref InstancePort
          Protocol: HTTP
      Tags:
      - Key: Name
        Value: MagentoWebserverALB
Outputs:
  PublicLoadBalancer:
    Description: 'RDSSubnet'
    Value: !Ref PublicLoadBalancer