Parameters:
  PrivateMainSubnet:
    Description: The CIDR block for the Public network
    Type: String
  PrivateSecondarySubnet:
    Description: The CIDR block for the Public network
    Type: String
Resources:    
  PrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    #DependsOn: AttachGatewayToVPC
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds:
      - Ref: PrivateMainSubnet
      - Ref: PrivateSecondarySubnet

Outputs:
  PrivateSubnetGroup:
    Description: 'PrivateSubnetGroup'
    Value: !Ref PrivateSubnetGroup